/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author logon
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoModelo = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        boxEX = new javax.swing.JRadioButton();
        boxELX = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        boxPortas2 = new javax.swing.JRadioButton();
        boxPortas4 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        checkArCond = new javax.swing.JCheckBox();
        checkDir = new javax.swing.JCheckBox();
        checkTrio = new javax.swing.JCheckBox();
        checkTeto = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        buttonComprar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(100, 80, 100, 100);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));
        jPanel1.setLayout(null);

        grupoModelo.add(boxEX);
        boxEX.setText("EX");
        boxEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEXActionPerformed(evt);
            }
        });
        jPanel1.add(boxEX);
        boxEX.setBounds(20, 30, 37, 23);

        grupoModelo.add(boxELX);
        boxELX.setText("ELX");
        jPanel1.add(boxELX);
        boxELX.setBounds(20, 60, 43, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 140, 110);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Portas"));
        jPanel2.setLayout(null);

        buttonGroup1.add(boxPortas2);
        boxPortas2.setText("2 Portas");
        boxPortas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPortas2ActionPerformed(evt);
            }
        });
        jPanel2.add(boxPortas2);
        boxPortas2.setBounds(12, 23, 65, 23);

        buttonGroup1.add(boxPortas4);
        boxPortas4.setText("4 Portas");
        jPanel2.add(boxPortas4);
        boxPortas4.setBounds(12, 64, 65, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(180, 20, 130, 110);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcionais"));
        jPanel3.setLayout(null);

        checkArCond.setText("Ar Condicionado");
        jPanel3.add(checkArCond);
        checkArCond.setBounds(12, 23, 103, 23);

        checkDir.setText("Dir Hidráulica");
        checkDir.setToolTipText("");
        jPanel3.add(checkDir);
        checkDir.setBounds(12, 64, 87, 23);

        checkTrio.setText("Trio Elétrico");
        jPanel3.add(checkTrio);
        checkTrio.setBounds(12, 105, 81, 23);

        checkTeto.setText("Teto Solar");
        jPanel3.add(checkTeto);
        checkTeto.setBounds(123, 64, 75, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 160, 210, 150);

        jLabel1.setText("Quantidade");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 200, 70, 14);
        getContentPane().add(txtQtd);
        txtQtd.setBounds(320, 200, 59, 20);

        buttonComprar.setText("Comprar");
        buttonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonComprarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonComprar);
        buttonComprar.setBounds(260, 260, 73, 23);

        jLabel2.setText("Valor: R$");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 300, 50, 14);
        getContentPane().add(txtValor);
        txtValor.setBounds(320, 290, 70, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEXActionPerformed

    private void boxPortas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPortas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPortas2ActionPerformed

    private void buttonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComprarActionPerformed
        String quantidade;
        double valor = 0;
        double ovalor = 0;
        quantidade = txtQtd.getText();
        
        if(boxEX.isSelected() && boxPortas2.isSelected()) {valor += 18021 * Double.parseDouble(quantidade);}
        if(boxEX.isSelected() && boxPortas4.isSelected()) {valor +=19107 * Double.parseDouble(quantidade);}
        if(boxELX.isSelected() && boxPortas2.isSelected()) {valor += 21235 * Double.parseDouble(quantidade);}
        if(boxELX.isSelected() && boxPortas4.isSelected()) {valor += 20450 * Double.parseDouble(quantidade);}
        
        if(checkArCond.isSelected()) {ovalor += 3270;}
        if(checkDir.isSelected()) {ovalor += 2500;}
        if(checkTrio.isSelected()) {ovalor += 750;}
        if(checkTeto.isSelected()) {ovalor += 4218;}
        
        double resultado = valor + ovalor;
        String soma = (Double.toString(resultado));
        
        txtValor.setText(soma);
        
        
        
        
    }//GEN-LAST:event_buttonComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boxELX;
    private javax.swing.JRadioButton boxEX;
    private javax.swing.JRadioButton boxPortas2;
    private javax.swing.JRadioButton boxPortas4;
    private javax.swing.JButton buttonComprar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkArCond;
    private javax.swing.JCheckBox checkDir;
    private javax.swing.JCheckBox checkTeto;
    private javax.swing.JCheckBox checkTrio;
    private javax.swing.ButtonGroup grupoModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JLabel txtValor;
    // End of variables declaration//GEN-END:variables
}
